version: "3.8"

x-stack-environment: &stack-environment
  CLUSTER_NAME: $CLUSTER_NAME

x-deploy-defaults: &deploy-defaults
  update_config:
    delay: 10s
    order: start-first
  restart_policy:
    condition: on-failure

networks:
  traefik-net:
    name: traefik-net
    external: true

services:
  registry:
    image: registry:2
    networks:
      - default
      - traefik-net
    environment:
      <<: *stack-environment
      REGISTRY_PROXY_REMOTEURL: https://ghcr.io
    deploy:
      <<: *deploy-defaults
      labels:
        - traefik.enable=true
        - traefik.http.routers.registry.rule=Host(`registry.$ROOT_DOMAIN`)
        - traefik.http.routers.registry.service=registry
        - traefik.http.services.registry.loadbalancer.server.port=5000
