version: "2.1"

volumes:
  acme_data:

networks:
  default:
    name: infra
    external: true

services:
  traefik:
    image: traefik:v2.9
    environment:
      - CLOUDFLARE_DNS_API_TOKEN=$CLOUDFLARE_DNS_API_TOKEN
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entryPoints.web.forwardedheaders.trustedips=$TRUSTED_IPS
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entryPoints.websecure.forwardedheaders.trustedips=$TRUSTED_IPS
      - --entrypoints.websecure.http.tls
      - --entrypoints.websecure.http.tls.certresolver=zerossl
      - --entrypoints.websecure.http.tls.domains[0].main=$ROOT_DOMAIN
      - --entrypoints.websecure.http.tls.domains[0].sans=*.$ROOT_DOMAIN
      - --certificatesresolvers.zerossl.acme.email=lujjjh@gmail.com
      - --certificatesresolvers.zerossl.acme.storage=/acme/zerossl.json
      - --certificatesresolvers.zerossl.acme.dnschallenge
      - --certificatesresolvers.zerossl.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.zerossl.acme.caserver=https://acme.zerossl.com/v2/DV90
      - --certificatesresolvers.zerossl.acme.eab.kid=$ZEROSSL_ACME_EAB_KID
      - --certificatesresolvers.zerossl.acme.eab.hmacencoded=$ZEROSSL_ACME_EAB_HMACENCODED
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - acme_data:/acme
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 60

  whoami:
    image: traefik/whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.$ROOT_DOMAIN`)
