version: "2.1"

volumes:
  acme_data:

networks:
  default:
    name: infra
    external: true

services:
  traefik:
    image: traefik:v2.9
    environment:
      - CLOUDFLARE_DNS_API_TOKEN=$CLOUDFLARE_DNS_API_TOKEN
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entryPoints.web.forwardedHeaders.trustedIPs=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22,2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls
      - --entrypoints.websecure.http.tls.certresolver=zerossl
      - --entrypoints.websecure.http.tls.domains[0].main=$ROOT_DOMAIN
      - --entrypoints.websecure.http.tls.domains[0].sans=*.$ROOT_DOMAIN
      - --certificatesresolvers.zerossl.acme.email=lujjjh@gmail.com
      - --certificatesresolvers.zerossl.acme.storage=/acme/zerossl.json
      - --certificatesresolvers.zerossl.acme.dnschallenge
      - --certificatesresolvers.zerossl.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.zerossl.acme.caserver=https://acme.zerossl.com/v2/DV90
      - --certificatesresolvers.zerossl.acme.eab.kid=$ZEROSSL_ACME_EAB_KID
      - --certificatesresolvers.zerossl.acme.eab.hmacencoded=$ZEROSSL_ACME_EAB_HMACENCODED
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - acme_data:/acme
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 60

  whoami:
    image: traefik/whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.$ROOT_DOMAIN`)
