global:
  external_labels:
    cluster_name: $CLUSTER_NAME

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: node
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: traefik
    static_configs:
      - targets: ["traefik:8080"]

remote_write:
  - url: $PROMETHEUS_REMOTE_ENDPOINT
    basic_auth:
      username: $GRAFANA_USERNAME
      password: $GRAFANA_API_KEY
