global:
  external_labels:
    cluster_name: $CLUSTER_NAME

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "dockerswarm"
    scrape_interval: 15s
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
        regex: .+
        action: keep
      - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
        target_label: job
      - source_labels: [__meta_dockerswarm_service_label_prometheus_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels:
          [__address__, __meta_dockerswarm_service_label_prometheus_port]
        target_label: __address__
        separator: ";"
        regex: '([^:]+):\d+;(\d+)'
        replacement: "\${1}:\${2}"
      - source_labels:
          [__meta_dockerswarm_service_mode, __meta_dockerswarm_node_hostname]
        target_label: instance
        separator: ";"
        regex: "global;(.*)"
        replacement: "\${1}"
      - source_labels:
          [__meta_dockerswarm_service_mode, __meta_dockerswarm_service_name]
        target_label: instance
        separator: ";"
        regex: "replicated;(.*)"
        replacement: "\${1}"

remote_write:
  - url: $PROMETHEUS_REMOTE_ENDPOINT
    basic_auth:
      username: $GRAFANA_USERNAME
      password: $GRAFANA_API_KEY
